[options]
addons_path = /usr/lib/python3/dist-packages/odoo/addons,/mnt/extra-addons
log-db = False
syslog = False
log-level = info
admin_passwd = $pbkdf2-sha512$600000$6H3PuVfq3VvL2bsXohSCcA$O3uVo0kAUeUUFyktMj2QW8odKC2B7Y/fGf3tu0ZBgFGEdy05aAEFlWlk69eTPMY6w/qlpvuZMk7CHOaIoXJm5w

